StudyGroupEditor/Controllers/AddGroupController.cs
using Microsoft.AspNetCore.Mvc;
using StudyGroupEditor.Models.DatabaseModels;
using StudyGroupEditor.Models.ViewModels;

namespace StudyGroupEditor.Controllers;

public class AddGroupController : Controller
{
    private readonly UniversityContext _universityContext;
    
    public AddGroupController(UniversityContext universityContext)
    {
        _universityContext = universityContext;
    }
    
    public IActionResult Index()
    {
        return View(new CreatePageModel(_universityContext.Teachers));
    }
    
    [HttpPost]
    public async Task<IActionResult> CreateGroup(Group group, Employee employee)
    {
        _universityContext.Groups.Add(group);
        await _universityContext.SaveChangesAsync();
        return RedirectToAction("Index", "EditGroup", group);
    }
}

StudyGroupEditor/Views/AddGroup/Index.cshtml
@model StudyGroupEditor.Models.ViewModels.CreatePageModel
<h1 class="display-4">Создать учебную группу</h1>
<h2>Учебные группы > Создать учебную группу</h2>
<form asp-action="CreateGroup" asp-controller="AddGroup">
    <p>
        <label asp-for="Group.TeacherId">Преподаватель</label><br />
        @* <input type="text" asp-for="Teacher" /> *@
        <select asp-for="Group.TeacherId" asp-items="Model.TeachersSelectList"></select>
    </p>
    <p>
        <label asp-for="Group.Name">Название учебной группы</label><br />
        <input type="text" asp-for="Group.Name" />
    </p>
    <p>
        <input type="submit" value="Создать"/>
    </p>
</form>