StudyGroupEditor/Controllers/AddStudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StudyGroupEditor.Models.DatabaseModels;
using StudyGroupEditor.Models.ViewModels;

namespace StudyGroupEditor.Controllers;

public class AddStudentController : Controller
{
    private readonly UniversityContext _universityContext;

    public AddStudentController(UniversityContext universityContext)
    {
        _universityContext = universityContext;
    }
    
    public async Task<IActionResult> Index(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var groups = 
            await _universityContext.Groups
                .Include(g => g.Teacher)
                .ThenInclude(t => t.Organizations)
                .ThenInclude(org => org.Employees)
                .Include(g => g.Employees)
                .ThenInclude(e => e.Organization)
                .ToListAsync();
        
        var group = groups.FirstOrDefault(g => g.GroupId == id.Value);
        
        if (group == null)
        {
            return NotFound();
        }
        
        return View(new AddStudentPageModel(group));
    }
    
    public async Task<IActionResult> GetEmployees(int id)
    {
        var organizations =
            await _universityContext.Organizations
                .Include(org => org.Employees)
                .ToListAsync();;
        
        var organization = organizations.FirstOrDefault(org => org.OrganizationId == id);
        
        if (organization == null)
        {
            return NotFound();
        }
        
        return PartialView(organization.Employees.ToList());
    }
    

    [HttpPost]
    public async Task<IActionResult> AddStudent(Employee employee)
    {
        _universityContext.Employees.Add(employee);
        await _universityContext.SaveChangesAsync();
        return RedirectToAction("Index", "EditGroup", employee);
    }
}

StudyGroupEditor/Controllers/EditGroupController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StudyGroupEditor.Models.DatabaseModels;

namespace StudyGroupEditor.Controllers;

public class EditGroupController : Controller
{
    private readonly UniversityContext _universityContext;
    
    public EditGroupController(UniversityContext universityContext)
    {
        _universityContext = universityContext;
    }
    
    // public IActionResult Index(Group group)
    // {
    //     //return View(new EditGroupModel(group));
    //     return View(group);
    // }
    public async Task<IActionResult> Index(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var groups = 
            await _universityContext.Groups
                .Include(g => g.Teacher)
                .Include(g => g.Employees)
                .ThenInclude(e => e.Organization)
                .ToListAsync();
        
        var group = groups.FirstOrDefault(g => g.GroupId == id.Value);
        
        if (group == null)
        {
            return NotFound();
        }
        
        return View(group);
    }

    [HttpPost]
    public ActionResult EditGroupName(Group group)
    {
        _universityContext.Entry(group).State = EntityState.Modified;
        _universityContext.SaveChanges();
        return RedirectToAction(nameof(Index), group);
    }
    
    // public IActionResult EditGroupName()
    // {
    //     throw new NotImplementedException();
    // }
    // [HttpPost]
    // [ValidateAntiForgeryToken]
    // public async Task<IActionResult> EditGroupName(int id, [Bind("GroupID,Name")]Group group)
    // {
    //     string newName = group.Name;
    //     
    //     if (id != group.GroupId)
    //     {
    //         return NotFound();
    //     }
    //
    //
    //     group = await _universityContext.Groups.FindAsync(id);
    //     if (group == null)
    //     {
    //         return NotFound();
    //     }
    //
    //     group.Name = newName;
    //     
    //     // if (ModelState.IsValid)
    //     // {
    //         try
    //         {
    //             _universityContext.Update(group);
    //             await _universityContext.SaveChangesAsync();
    //         }
    //         catch (DbUpdateConcurrencyException)
    //         {
    //             if (!GroupExists(group.GroupId))
    //             {
    //                 return NotFound();
    //             }
    //             else
    //             {
    //                 throw;
    //             }
    //         }
    //         return RedirectToAction(nameof(Index), group);
    //     //}
    //     return RedirectToAction(nameof(Index), group);
    // }

    private bool GroupExists(int groupGroupId)
    {
        return true;
    }
    
    public async Task<IActionResult> DeleteStudent(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var group = await _universityContext.Groups.FindAsync(id);
        if (group == null)
        {
            return NotFound();
        }
        return RedirectToAction("Index", "EditGroup", group);
    }
}

StudyGroupEditor/Views/EditGroup/Index.cshtml
@* @model StudyGroupEditor.Models.ViewModels.EditGroupModel *@
@using StudyGroupEditor.Controllers
@model StudyGroupEditor.Models.DatabaseModels.Group
<h1 class="display-4">Создать учебную группу</h1>
<h2>Учебные группы > Создать учебную группу</h2>
    <p>
        <label> @("Название учебной группы: " + Model.Name) </label><br/>
    </p>
<form asp-action="EditGroupName" method="post" asp-controller="EditGroup" asp-route-id="@Model.GroupId">
    <input type="hidden" asp-for="GroupId" />
    <input type="hidden" asp-for="CourseId" />
    <input type="hidden" asp-for="TeacherId" />
    <input type="hidden" asp-for="Teacher" />
    <input type="hidden" asp-for="Course" />
    <input type="hidden" asp-for="Employees" />
    <p>
        <label asp-for="Name">Название учебной группы</label><br/>
        <input type="text" asp-for="Name"/>
    </p>
    <p>
        <input type="submit" value="Сохранить изменения"/>
    </p>
</form>
<table class="table">
    <tr>
        <th>Студент</th>
        <th>Организация</th>
        <th></th>
    </tr>
    @foreach (var employee in Model.Employees)
    {
        <tr>
            <td>@employee.Name</td>
            <td>@employee.Organization.Name</td>
            <td> <form method="post">
                <a asp-action="DeleteStudent" asp-route-id="@employee.EmployeeId">Удалить из группы</a>
            </form></td>
        </tr>
    }
</table>
<a asp-controller="AddStudent" asp-action="Index" asp-route-id="@Model.GroupId">Добавить студента в учебную группу</a>